version: "3"
services:
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
