#!/bin/bash

if ! which mockgen 1>&2 > /dev/null; then
  echo "Please install mockgen: go install github.com/golang/mock/mockgen@v1.6.0"
  exit 1
fi

rm -rfv mocks
mkdir mocks

function gen() {
  path="$1"
  filename="$(basename "$path")"
  mockgen -package=mocks -source="$path" > "mocks/${filename%.*}_mocks.go"
}

gen "storage/provider.go"
gen "redis/redis.go"
mockgen -package=mocks "github.com/heyvito/redlock-go" Redlock > "mocks/redlock-go_mocks.go"
