on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        kind: [unit, integration]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - name: Run tests
        run: script/full-test ${{ matrix.kind }}

  build:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build . -t cocov/cache:dev -f Dockerfile

      - name: Push docker image
        run: docker push cocov/cache:dev

#      - name: Trigger update
#        uses: appleboy/ssh-action@v0.1.6
#        with:
#          host: ${{ secrets.DEPLOY_HOST }}
#          username: ${{ secrets.DEPLOY_USERNAME }}
#          key: ${{ secrets.DEPLOY_KEY }}
#          port: ${{ secrets.DEPLOY_PORT }}
#          script: cocov/update
