on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:alpine
        ports:
          - "6379:6379"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 'stable'
      - name: Start local MinIO server
        run: docker run -d -p 9000:9000 --name minio minio/minio server /data
      - name: Run tests
        run: go test ./...
  build:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build . -t cocov/cache:dev -f Dockerfile

      - name: Push docker image
        run: docker push cocov/cache:dev

#      - name: Trigger update
#        uses: appleboy/ssh-action@v0.1.6
#        with:
#          host: ${{ secrets.DEPLOY_HOST }}
#          username: ${{ secrets.DEPLOY_USERNAME }}
#          key: ${{ secrets.DEPLOY_KEY }}
#          port: ${{ secrets.DEPLOY_PORT }}
#          script: cocov/update
